- name: "Setup wordpress"
  hosts: prod
  tasks:
    - name: "[wordpress] - check if exist"
      stat:
        path: "/var/www/html/wordpress/"
      register: check_wordpress

    - name: "[wordpress] - download tar.gz"
      unarchive:
        src: "{{ wordpress_source }}"
        dest: "/var/www/html/"
        remote_src: yes
      when: check_wordpress.stat.exists == False 


    - name: "[wordpress] - drop file default index.html"
      file:
        path: "/var/www/html/index.html"
        state: absent


    - name: "[wordpress] - check if exist"
      stat:
        path: "/var/www/html/wordpress/wp-config-sample.php"
      register: check_sample

    - name: "[wordpress] - rename wp-config-sample.php"
      command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
      when: check_sample.stat.exists == True


    - name: "[wordpress] - modify wp-config.php"
      lineinfile:
        dest: "/var/www/html/wordpress/wp-config.php"
        regexp: "{{ item.search }}"
        line: "{{ item.new }}"
        backrefs: yes
      with_items:
        - {'search': '^(.*)database_name_here(.*)$', 'new': '\1{{ mysql_db }}\2'}
        - {'search': '^(.*)username_here(.*)$', 'new': '\1{{ mysql_user }}\2'}
        - {'search': '^(.*)password_here(.*)$', 'new': '\1{{ mysql_password }}\2'}